import localFont from "next/font/local";
import Image from "next/image";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-600 text-white p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center">
              <Image
                src="/logo.svg"
                alt="Shopping Cart Logo"
                width={40}
                height={40}
                className="mr-2"
              />
              <h1 className="text-2xl">Shopping List App</h1>
            </div>
            <nav>
              <ul className="flex space-x-4 justify-center">
                <li><a href="/" className="hover:underline">Home</a></li>
                <li><a href="/about" className="hover:underline">About</a></li>
                <li><a href="/list-detail" className="hover:underline">Mock List Detail</a></li>
                {/* Add more links as needed */}
              </ul>
            </nav>
            <select className="bg-white text-blue-600 px-2 py-1 rounded">
              <option value="">Select User</option>
              <option value="user1">Michal</option>
              <option value="user2">Žalud</option>
            </select>
          </div>
        </header>
        <main className="p-4">
          {children}
        </main>
        <footer className="bg-gray-800 text-white p-4 text-center">
          © 2024 Shopping List App
        </footer>
      </body>
    </html>
  );
}
